---
title: "Read Me"
output: html_document
---
This is the repository for the Peer reviewed project developed for Developing Data Products.

It uses the Fuel Economy data from the Applied Predictive Modeling package in R.
The http://fueleconomy.gov website, run by the U.S. Department of Energy's Office of Energy Efficiency and Renewable Energy and the U.S. Environmental Protection Agency, lists different estimates of fuel economy for passenger cars and trucks. For each vehicle, various characteristics are recorded such as the engine displacement or number of cylinders. Along with these values, laboratory measurements are made for the city and highway miles per gallon (MPG) of the car.

Predictors extracted from the website include: EngDispl, NumCyl, Transmission, AirAspirationMethod, NumGears, TransLockup, TransCreeperGear, DriveDesc, IntakeValvePerCyl, ExhaustValvesPerCyl, CarlineClassDesc, VarValveTiming and VarValveLift. The outcome used in the book is in column FE and is the unadjusted highway data.

cars2010  
data in cars from model year 2010.

cars2011	
cars introduced in 2011 that were not in the model year 2010 data.

cars2012	
cars introduced in 2012 that were not in the model year 2010 or 2011 data

